name: quantforge-ai
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - pydantic
  - fastapi
  - uvicorn
  - redis
  - cython
  - pip:
      - llama-cpp-python
      - transformers
      - accelerate
      - onnxruntime-openvino
      - torch==2.2.0
      - torchvision
      - torchaudio
      - aiohttp
      - python-dotenv
      - darts
      - scikit-learn